### ISSUE TITLE
JS is a mess

### ISSUE THREAD

**Issue by zufrieden** [antistatique/laliberte-150#1]
### 💬 Describe the task
Clean JS mess

### ✅ Todo
Steps to achieve the task:
- [x] Separate JS file for swup plugins and themes
- [x] Clean folded [library](https://tympanus.net/Tutorials/FoldingDOM/index5.html)
- [x] Make the page work when coming from swup
